spring:
  application:
    name: oauth2-soc-log
  security:
    user:
      name: gofar
      password: gofar
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ligreH3iTjWTJvCR
            client-secret: b8738825a5e0258169478c31524fece416b928f9
          facebook:
            client-id: 470881822531759
            client-secret: d1b3cd1f7e550115a236309e6d8ecd2b

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        security: trace

server:
  port: 6070