spring:
  application:
    name: oauth2-soc-log
  security:
    user:
      name: gofar
      password: gofar

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        security: trace

server:
  port: 6070